var u=Object.defineProperty,R=Object.defineProperties,A=Object.getOwnPropertyDescriptor,C=Object.getOwnPropertyDescriptors,P=Object.getOwnPropertyNames,y=Object.getOwnPropertySymbols;var S=Object.prototype.hasOwnProperty,w=Object.prototype.propertyIsEnumerable;var v=(t,e,r)=>e in t?u(t,e,{enumerable:!0,configurable:!0,writable:!0,value:r}):t[e]=r,n=(t,e)=>{for(var r in e||(e={}))S.call(e,r)&&v(t,r,e[r]);if(y)for(var r of y(e))w.call(e,r)&&v(t,r,e[r]);return t},i=(t,e)=>R(t,C(e)),T=t=>u(t,"__esModule",{value:!0});var x=(t,e)=>{for(var r in e)u(t,r,{get:e[r],enumerable:!0})},J=(t,e,r,a)=>{if(e&&typeof e=="object"||typeof e=="function")for(let s of P(e))!S.call(t,s)&&(r||s!=="default")&&u(t,s,{get:()=>e[s],enumerable:!(a=A(e,s))||a.enumerable});return t};var b=(t=>(e,r)=>t&&t.get(e)||(r=J(T({}),e,1),t&&t.set(e,r),r))(typeof WeakMap!="undefined"?new WeakMap:0);var N={};x(N,{default:()=>k});var q=require("@raycast/api");var f=require("react"),p=require("@raycast/api");function c(state,long=!1){let evalResult,result,type,query=state.query.trim()??"";try{try{try{evalResult=JSON.parse(query)}catch(_){evalResult=eval(`(${query})`)}}catch(_){evalResult=eval(query)}}catch(t){type="error",evalResult=t.toString()}return type||=L(evalResult),d(evalResult)||(console.log(evalResult),result=JSON.stringify(evalResult,(t,e)=>d(e)&&JSON.stringify(e)==="null"?e?.toString()??e:e,long?2:void 0)),result||=evalResult?.toString()??"undefined",i(n({},state),{type,result})}function L(t){return{}.toString.call(t).match(/\s([a-zA-Z]+)/)?.[1].toLowerCase()??"undefined"}function d(t){return t!==Object(t)}var l=require("@raycast/api");function m(t){return _jsx(l.ActionPanel,{title:"Evaluation result"},_jsx(l.ActionPanel.Section,null,t.state?.result&&_jsx(l.CopyToClipboardAction,{title:"Copy Result to Clipboard",content:t.state.result}),t.state?.query&&_jsx(l.CopyToClipboardAction,{title:"Copy Code to Clipboard",content:t.state.query})))}function g(){let[t,e]=(0,f.useState)({query:"",result:"",type:""});return(0,f.useEffect)(()=>{let r=c(t);e(r)},[t.query]),_jsx(p.List,{searchBarPlaceholder:"Type some Javascript to Evaluate",onSearchTextChange:r=>{e(a=>i(n({},a),{query:r}))}},(t?.query?.length??0)===0?null:_jsx(p.List.Item,{title:t?.result??"undefined",subtitle:t?.type??"undefined",accessoryTitle:"JS Evaluation",actions:_jsx(m,{state:t}),icon:"command-icon.png"}))}var E=require("react"),o=require("@raycast/api");function h(){let[t,e]=(0,E.useState)({query:"",result:"",type:""});return _jsx(o.List,{searchBarPlaceholder:"Type some Javascript to Evaluate and press return",onSearchTextChange:r=>{e(a=>i(n({},a),{query:r}))}},(t?.query?.length??0)===0?null:_jsx(o.List.Item,{title:`Evaluate: ${t?.query}`,accessoryTitle:"\u23CE  to evaluate",actions:_jsx(o.ActionPanel,{title:"Evaluation result"},_jsx(o.PushAction,{title:"Show Evaluation",icon:"command-icon.png",target:_jsx($,{state:t})})),icon:"command-icon.png"}))}function $(t){let e=c(t.state,!0),r=`
  ### Code:
  \`\`\`
  ${e.query}
  \`\`\`
  
  ### Evaluation:
  \`\`\`
  ${e?.result??"undefined"}
  \`\`\`
  
  ### Type:
  \`\`\`
  ${e?.type??"undefined"}
  \`\`\`
  `;return _jsx(o.Detail,{markdown:r,actions:_jsx(m,{state:e})})}var O=(0,q.getPreferenceValues)()?.fastEvaluation??!1,k=()=>_jsx(O?g:h,null);module.exports=b(N);0&&(module.exports={});
