#!/bin/sh
# Run by github/github codespaces after starting

# Always want to use Fish as my default shell (e.g. for SSH)
if [ $(echo $SHELL) != $(which fish) ]
then
  echo "Using Fish shell"
  chsh -s $(which fish 2>/dev/null)
fi
