#!/bin/bash

echo
echo
echo "##################################################"
echo "####### Dotfiles Setup ###########################"
echo "##################################################"
echo
echo

# Install dotfiles into home directory
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
DOTFILESDIR=$(dirname $SCRIPTPATH)
DOTFILES=$(ls -a $DOTFILESDIR)

echo "SCRIPTPATH: $SCRIPTPATH"
echo "DOTFILESDIR: $DOTFILESDIR"
echo "DOTFILES: $DOTFILES"

# Move dotfiles to home directory
echo
echo "🔗 Linking dotfiles to home directory "
echo

for DOTFILE in $DOTFILES; do
  HOMEFILE="$HOME/$DOTFILE"
  [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
  DIRFILE="$DOTFILESDIR/$DOTFILE"


  # Don't mess with Codespaces' default GPG/SSH setup.
  if [ -n "$CODESPACES" ]
  then
    echo $DOTFILE | egrep -q '^(gnupg|ssh)/' && continue
  fi

  # Don't try to install documentation/script/lock files
  echo $DOTFILE | egrep -q '(\.\/$|^\.git\/$|^script\/$|setup|\.txt$|\.md$)' && continue
  
  echo "DOTFILE $DOTFILE"  
  echo "DIRFILE $DIRFILE"
  echo "HOMEFILE $HOMEFILE"

  if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
  then
    ln -sfv "$DIRFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE" 2>/dev/null
    ln -sv "$DIRFILE" "$HOMEFILE"
  fi

  echo 
done

HOME_DOTFILES_ALIAS="$HOME/.dotfiles"

echo 
echo "🔗 Creating a symlink in ~/.dotfiles to this dotfiles repo"
echo

if [ -L "$HOME_DOTFILES_ALIAS" ] && ! [ -d $DOTFILESDIR ]
then
  ln -sfv "$DOTFILESDIR" "$HOME_DOTFILES_ALIAS"
else
  rm -rv "$HOME_DOTFILES_ALIAS" 2>/dev/null
  ln -sv "$DOTFILESDIR" "$HOME_DOTFILES_ALIAS"
fi



# Fix up permissions for Codespaces
if [ -n "$CODESPACES" ]
then
  chmod 700 /workspaces
fi

$SCRIPTPATH/install.sh

$SCRIPTPATH/install-fish.sh

fish $SCRIPTPATH/setup.fish

echo
echo
echo "##################################################"
echo "####### DONE! ####################################"
echo "##################################################"
echo
echo